In [70]:
import pandas as pd
import numpy as np

In [15]:
# 3(b)
sal = pd.read_csv('Salaries.csv')
sal

yearID teamID lgID   playerID    salary
0        1985    ATL   NL  barkele01    870000
1        1985    ATL   NL  bedrost01    550000
2        1985    ATL   NL  benedbr01    545000
3        1985    ATL   NL   campri01    633333
4        1985    ATL   NL  ceronri01    625000
...       ...    ...  ...        ...       ...
25570    2015    WAS   NL  treinbl01    512800
25571    2015    WAS   NL  ugglada01    507500
25572    2015    WAS   NL  werthja01  21000000
25573    2015    WAS   NL  zimmejo02  16500000
25574    2015    WAS   NL  zimmery01  14000000

[25575 rows x 5 columns]

In [19]:
#3(c)
sal_id = pd.read_csv('Salaries.csv', index_col = 'playerID',skiprows = [1])
sal_id

yearID teamID lgID    salary
playerID                               
bedrost01    1985    ATL   NL    550000
benedbr01    1985    ATL   NL    545000
campri01     1985    ATL   NL    633333
ceronri01    1985    ATL   NL    625000
chambch01    1985    ATL   NL    800000
...           ...    ...  ...       ...
treinbl01    2015    WAS   NL    512800
ugglada01    2015    WAS   NL    507500
werthja01    2015    WAS   NL  21000000
zimmejo02    2015    WAS   NL  16500000
zimmery01    2015    WAS   NL  14000000

[25574 rows x 4 columns]

In [32]:
#3(d)
sal_team = sal_id[sal_id['teamID'].isin(['ATL','HOU'])]
sal_sal = sal_team[sal_team['salary'] > 1000000]
sal_sal

yearID teamID lgID   salary
playerID                              
hornebo01    1985    ATL   NL  1500000
murphda05    1985    ATL   NL  1625000
suttebr01    1985    ATL   NL  1354167
ryanno01     1985    HOU   NL  1350000
hornebo01    1986    ATL   NL  1800000
...           ...    ...  ...      ...
quallch01    2015    HOU   AL  3000000
rasmuco01    2015    HOU   AL  8000000
singljo02    2015    HOU   AL  2000000
sippto01     2015    HOU   AL  2400000
valbulu01    2015    HOU   AL  4200000

[595 rows x 4 columns]

In [69]:
#3(e)
sal_atl = sal_id[sal_id['teamID'].isin(['ATL'])]
sal_atl['salary'].describe()

count    8.850000e+02
mean     2.207749e+06
std      3.434320e+06
min      6.000000e+04
25%      3.000000e+05
50%      6.000000e+05
75%      2.400000e+06
max      1.606180e+07
Name: salary, dtype: float64

In [59]:
# 3(f)
sal_header = list(sal)
dic = {}
for i in sal_header:
    dic[i] = list(sal[i])

dict_keys(['yearID', 'teamID', 'lgID', 'playerID', 'salary'])

In [68]:
# 3(g)
sal_from_dic = pd.DataFrame.from_dict(dic)
sal_from_dic.rename(columns={'yearID': 'a','teamID': 'b','lgID': 'c', 'playerID':'d', 'salary': 'e'})

a    b   c          d         e
0      1985  ATL  NL  barkele01    870000
1      1985  ATL  NL  bedrost01    550000
2      1985  ATL  NL  benedbr01    545000
3      1985  ATL  NL   campri01    633333
4      1985  ATL  NL  ceronri01    625000
...     ...  ...  ..        ...       ...
25570  2015  WAS  NL  treinbl01    512800
25571  2015  WAS  NL  ugglada01    507500
25572  2015  WAS  NL  werthja01  21000000
25573  2015  WAS  NL  zimmejo02  16500000
25574  2015  WAS  NL  zimmery01  14000000

[25575 rows x 5 columns]

In [81]:
# 4(a)
a_list = [[1, 2], [3, 4]]
np_array = np.array(a_list)
np_array

array([[1, 2],
       [3, 4]])

In [85]:
#4(b)
np_array.ndim

2

In [84]:
np_array.shape

(2, 2)

In [86]:
np_array.size

4

In [87]:
np_array.dtype

dtype('int64')

In [88]:
np_array.itemsize

8

In [89]:
# 4(c) reshape
reshape_array = np_array.reshape(4)
reshape_array

array([1, 2, 3, 4])

In [91]:
# 4(c) flatten
np_array.flatten()

array([1, 2, 3, 4])

In [ ]:
# 5(a)
